---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# MADRES

<!-- badges: start -->
<!-- badges: end -->

The MADRES package is a small suite of helper functions for working with data from the MADRES Center at USC. Much of this package is dataset-specific, and not particularly useful outside of this research. Additional information is available on the MADRES servers, including a readme file with examples. Please check "/MADRES_DATA/MADRES R Package". 

The Maternal And Developmental Risks from Environmental and Social Stressors (MADRES) Center aims to understand the impact of environmental exposures and social stressors on the health of mothers and their children, and particularly how these exposures contribute to health disparities. Since its inception in 2015, the MADRES Center has recruited a cohort of over 900 women during pregnancy from four community health centers in Los Angeles. The majority of MADRES Study participants are Hispanic and report annual household incomes of less than $50,000. The study follows the women and children through the child’s fifth birthday. Key maternal health outcomes include pregnancy weight gain, as well as postpartum weight retention, depression, and cardiovascular disease risk in the years after birth. Key child health outcomes include early childhood obesity, respiratory health including asthma, neurodevelopment, and overall health.

If you're interested in our work, please check out our research at [https://madres.usc.edu/](https://madres.usc.edu/). 

## Installation

You can install the development version of MADRES from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("helenbfoley/MADRES")
```

There are lots of applications for these helper functions when setting up biosample datasets, as well as among the demographic and other data in MADRES. If you have requests for new functions or code snippets you find yourself copying all the time, reach out and we can add it to this package. 

Thanks for checking out MADRES!

Helen Foley
